### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by mehraf** [idleloop-github/Zebedee.apk#2]
Hi.
Source code compiles but does not work when user clicks on Start
even precompiled APK that is in the website does not work
tested on Samsung Galaxy S5 on Android 6.0.1

**Comment by idleloop-github** [comment]
Hi @mehraf 
Please, note that you need a valid **zebedee client text configuration file**, that is looked for by default on the root of your user space as a file named "**zebedee_parameters.txt**". You can select any other file with the button, *before* cllicking the button "start".

Bear in mind that this app is for skilful :-o  users who have previously configured a **remote zebedee-server**, and use the app as a **zebedee-client** to establish an encrypted tunnel with it. (The reverse can also be made, but is probably more tricky).

As a guide, you can test the remote and client ends of the tunnel on a PC, following [instructions at zebedee original site](http://www.winton.org.uk/zebedee/manual.html). This involves setting both IPs, listening port, selecting who initiates the connection, and the ports that will be redirected through the tunnel... Once everything runs on the PC, just copy the file to Android, select it, and run.

**Comment by mehraf** [comment]
I already have a server waiting for connections and i can connect to it via Windows os and binary version of zebedee compiled for android.
I put pre-configured file for client application. i use the same file to connect in Windows client and it works.
note that i do not see any errors in Logcat. the app just disappears without "force close" message.

**Comment by idleloop-github** [comment]
Maybe you're using a port below 1024 on the Android side? I can take a look at your file conf (erase confidential IPs and so if you wish): idleloop@yahoo.com

**Comment by mehraf** [comment]
Yes i have done that. Local port is above 1024. I have sent you an email containing the zbd config file.

**Comment by idleloop-github** [comment]
Ok, it seems the code ([jzbd](http://www.winton.org.uk/zebedee/download.html#jzbd)) does not allow for server keywords in a client configuration, and treats them as if they were unknown keywords, that is, a sudden close.
Maybe I'll take a look in a future version to provide an error message instead of this (unexpected) behaviour.
Thanks for the report!
